version: '3'

services:

  teamcity:
    image: jetbrains/teamcity-server:latest
    container_name: TeamCity
    restart: always 
    volumes:
      - ./data/teamcity/data:/data/teamcity_server/datadir
      - ./data/teamcity/logs:/opt/teamcity/logs
    ports:
      - "8111:8111"
    networks:
      - network

  agent1:
    build:
      context: ./
      dockerfile: ./agent.dockerfile
    container_name: TeamCity_Agent_1
    restart: always 
    volumes:
      - ./data/teamcity/agent/conf1:/data/teamcity_agent/conf
    environment:
      SERVER_URL: teamcity:8111
    networks:
      - network

  # agent2:
  #   build:
  #     context: ./
  #     dockerfile: ./agent.dockerfile
  #   container_name: TeamCity_Agent_2
  #   restart: always 
  #   volumes:
  #     - /efs/teamcity/agent/conf2:/data/teamcity_agent/conf
  #   environment:
  #     SERVER_URL: teamcity:8111
  #   networks:
  #     - network

  mysql:
    image: mysql:latest
    container_name: TeamCity_MySQL
    restart: always 
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: teamcity
      MYSQL_USER: teamcity
      MYSQL_PASSWORD: teamcity
    networks:
      - network

networks:
  network:
      driver: bridge
